;  AMPc for Windows - Distribucion WAMP
;  Copyright (C) 2025  Hu SpA ( https://hucreativa.cl )
;  
;  This file is part of AMPc for Windows.
;  
;  This Source Code Form is subject to the terms of the Mozilla Public
;  License, v. 2.0. If a copy of the MPL was not distributed with this file,
;  You can obtain one at http://mozilla.org/MPL/2.0/.
; ----------------------------------------------------------------------------
; components.ini - Informacion sobre los componentes.

; [nombre_del_componente]
;   version = Version del componente.
;   hash_file = SHA-256 de file.
;   file = Nombre del archivo principal del componente.
;   from_folder = Subcarpeta con archivos a instalar.
[ampc]
version = 0.20.0

[apache]
version = 2.4.66-251206
hash_file = 7d2fc2273a0b55a8e025b692b44b953a4eb18464a8d8a809832a5d01643ec76c
file = httpd-%version%-win64-VS17.zip
from_folder = Apache24

[mariadb]
version = 11.4.9
hash_file = 802f9f40a9dca774a3ba62f39c21093942954f178d6d7d458dc51453929bcdda
file = mariadb-%version%-winx64.zip
from_folder = mariadb-%version%-winx64

[php]
version = 8.4.16
hash_file = 5637d84718610497b6ae70e359133143225c9e0b629c7dfc36f5e1333a3806b2
file = php-%version%-Win32-vs17-x64.zip
from_folder = 

[cacert]
version = 25.12.02
hash_file = af5c129dbc59a6c44af3a4621f77e11ab71413b9d163867c7c4650b8ce171223
file = cacert.zip
from_folder = 